### ISSUE TITLE
Make the docs embeddable

### ISSUE THREAD

**Issue by kazk** [codewars/docs#308]
Replace outdated and unmaintained help tabs on Codewars.

When `?embedded=true`, add `html[data-embedded="true"]` as early as possible, so we can style differently.

```css
/* Hide navigation components when embedded. */
html[data-embedded="true"] {
  & .navbar,
  & .pagination-nav,
  & .footer,
  & div[class^="docSidebarContainer"],
  & div[class^="tableOfContents"] {
    display: none;
  }
}
```
(can also variant `embedded` and use `embedded:hidden`)

Also, allow overriding the theme with query parameter `?theme=dark|light` to match the user's setting on Codewars. This should simply change `html[data-theme]`.
